services:
  zbx72_database:
    image: mariadb:11.4
    container_name: zbx72_database
    environment:
      MARIADB_DATABASE: ${ZBX_DB_NAME}
      MARIADB_USER: ${ZBX_DB_USER}
      MARIADB_PASSWORD: ${ZBX_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${ZBX_DB_ROOT_PASSWORD}
    volumes:
      - zbx72_data:/var/lib/mysql
    networks:
      - zbx72_network
    restart: unless-stopped

  zbx72_server:
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    container_name: zbx72_server
    environment:
      DB_SERVER_HOST: zbx72_database
      MYSQL_DATABASE: ${ZBX_DB_NAME}
      MYSQL_USER: ${ZBX_DB_USER}
      MYSQL_PASSWORD: ${ZBX_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ZBX_DB_ROOT_PASSWORD}
    depends_on:
      - zbx72_database
    networks:
      - zbx72_network
    restart: unless-stopped

  zbx72_web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.2-latest
    container_name: zbx72_web
    environment:
      ZBX_SERVER_HOST: zbx72_server
      ZBX_SESSION_NAME: zbx72
      DB_SERVER_HOST: zbx72_database
      MYSQL_DATABASE: ${ZBX_DB_NAME}
      MYSQL_USER: ${ZBX_DB_USER}
      MYSQL_PASSWORD: ${ZBX_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ZBX_DB_ROOT_PASSWORD}
      PHP_TZ: Europe/Amsterdam
      ZBX_SERVER_NAME: "Zabbix 7.2"
    depends_on:
      - zbx72_database
      - zbx72_server
    ports:
      - "7272:8080"
    volumes:
      - ../banner:/usr/share/zabbix/modules/banner:Z
      - ../host_overview:/usr/share/zabbix/modules/host_overview:Z
    networks:
      - zbx72_network
    restart: unless-stopped

  zbx72_agent:
    image: zabbix/zabbix-agent2:alpine-7.2-latest
    container_name: zbx72_agent
    environment:
      ZBX_HOSTNAME: zbx72_agent
      ZBX_SERVER_HOST: zbx72_server
      ZBX_PASSIVE_ALLOW: false
    depends_on:
      - zbx72_database
      - zbx72_server
      - zbx72_web
    networks:
      - zbx72_network
    restart: unless-stopped

networks:
  zbx72_network:
    driver: bridge

volumes:
  zbx72_data:
