services:
  zbx70_database:
    image: mariadb:11.4
    container_name: zbx70_database
    environment:
      MARIADB_DATABASE: ${ZBX_DB_NAME}
      MARIADB_USER: ${ZBX_DB_USER}
      MARIADB_PASSWORD: ${ZBX_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${ZBX_DB_ROOT_PASSWORD}
    volumes:
      - zbx70_data:/var/lib/mysql
    networks:
      - zbx70_network
    restart: unless-stopped

  zbx70_server:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: zbx70_server
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zbx70_database
      MYSQL_DATABASE: ${ZBX_DB_NAME}
      MYSQL_USER: ${ZBX_DB_USER}
      MYSQL_PASSWORD: ${ZBX_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ZBX_DB_ROOT_PASSWORD}
    depends_on:
      - zbx70_database
    networks:
      - zbx70_network
    restart: unless-stopped

  zbx70_web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    container_name: zbx70_web
    environment:
      ZBX_SERVER_HOST: zbx70_server
      ZBX_SESSION_NAME: zbx70
      DB_SERVER_HOST: zbx70_database
      MYSQL_DATABASE: ${ZBX_DB_NAME}
      MYSQL_USER: ${ZBX_DB_USER}
      MYSQL_PASSWORD: ${ZBX_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ZBX_DB_ROOT_PASSWORD}
      PHP_TZ: Europe/Amsterdam
      ZBX_SERVER_NAME: "Zabbix 7.0"
    depends_on:
      - zbx70_database
      - zbx70_server
    ports:
      - "7070:8080"
    volumes:
      - ../banner:/usr/share/zabbix/modules/banner:Z
      - ../host_overview:/usr/share/zabbix/modules/host_overview:Z
    networks:
      - zbx70_network
    restart: unless-stopped

  zbx70_agent:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zbx70_agent
    environment:
      ZBX_HOSTNAME: zbx70_agent
      ZBX_SERVER_HOST: zbx70_server
      ZBX_PASSIVE_ALLOW: false
    depends_on:
      - zbx70_database
      - zbx70_server
      - zbx70_web
    networks:
      - zbx70_network
    restart: unless-stopped

networks:
  zbx70_network:
    driver: bridge

volumes:
  zbx70_data:
